spring:
  #配置数据源信息
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组，默认值即为master
      primary: master
      #严格匹配数据源，默认false，ture未匹配到，抛出异常，false使用默认数据源
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/mybatis-plus?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: password
        slave-1:
          url: jdbc:mysql://localhost:3306/mybatis-plus-1?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: password
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
