spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/mybatis-plus?characterEncoding=utf-8&useSSL=false&serverTimeZone=GMT%2B8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  # 设置mybatis-plus的全局配置,设置表的前缀
  global-config:
    db-config:
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
      # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic)
      logic-delete-field: is_deleted
      logic-delete-value: 1 #逻辑已删除值（默认为1）
      logic-not-delete-value: 0 #逻辑未删除值（默认为0）
  #配置类型别名所对应的包
  type-aliases-package: org.github.cocodx.entity
  # 扫描通用枚举的包
  type-enums-package: org.github.cocodx.enums
